import { Geist, Poppins } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/myComponents/header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});

export const metadata = {
  title: "Noticias App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${poppins.variable} antialiased bg-[#EAEAEA]`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
